version: '3'
services:
  web:
    build:                           # 构建自定义镜像
      context: .                   # 指定Dockerfile文件所在路径
      dockerfile: Dockerfile         # 指定Dockerfile文件名称
    image: shiro:550debug
    container_name: shiro550debug
    ports:
    - "8080:8080"
    - "5005:5005"
